/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

import java.util.List;
import javax.swing.ImageIcon;
import se.chalmers.ait.dat215.lab2.Ingredient;
import se.chalmers.ait.dat215.lab2.Recipe;
import se.chalmers.ait.dat215.lab2.RecipeDatabase;
import se.chalmers.ait.dat215.lab2.SearchFilter;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JScrollPane;

/**
 *
 * @author Joakim
 */
public class SingleRecipeView extends javax.swing.JFrame {
    
    private String name;
    private int servings;
    private int price;
    
    private String description;
    private List<Ingredient> ingredients;
    private Recipe recipe;
    private String ingrList;
    private static int nbrOfWindows;
    
    Dimension dim;
                
    
    
    /**
     * Creates new form SingleRecipeView
     */
    public SingleRecipeView(Recipe r) {
        this.recipe = r;
        dim  = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        jScrollPane2.setBackground(Color.WHITE);
        
        
        ImageIcon frameIcon = new ImageIcon(
        getClass().getResource("/RecipeSearch/resources/img.png"));
    
        setIconImage(frameIcon.getImage());
        this.setLocation(nbrOfWindows*40,nbrOfWindows*40);
        nbrOfWindows = (nbrOfWindows+1)%20;
        this.singleRecipeImage.setIcon((r.getImage(234,234)));
        this.singleRecipeTitle.setText(r.getName());
        this.singleRecipeServingsData.setText(((Integer)r.getServings()).toString()+" st");
        this.singleRecipePriceData.setText(((Integer)r.getPrice()).toString()+" kr");
        this.singleRecipeTimeData.setText(((Integer)r.getTime()).toString()+" min");
        this.singleRecipeDifficultyData.setText(r.getDifficulty());
        for (Ingredient i : r.getIngredients()){
            if (ingrList == null){
                ingrList = "<html>"+"<body>"+i.toString();         
            }
            else{
                ingrList = ingrList + "<br />"+i.toString();
            }  
        }
        ingrList = ingrList+"</body>"+"</html>";
        this.singleRecipeIngrData.setText(ingrList);
        this.singleRecipeDescData.setText("<html>"+r.getDescription());
        //this.singleRecipeDescData.setSize(jScrollPane1.getSize());
       
        
        
       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        singleRecipeShort = new javax.swing.JPanel();
        singleRecipeTitle = new javax.swing.JLabel();
        singleRecipeServings = new javax.swing.JLabel();
        singleRecipeTime = new javax.swing.JLabel();
        singleRecipePrice = new javax.swing.JLabel();
        singleRecipeServingsData = new javax.swing.JLabel();
        singleRecipeTimeData = new javax.swing.JLabel();
        singleRecipePriceData = new javax.swing.JLabel();
        singleRecipeDifficulty = new javax.swing.JLabel();
        singleRecipeDifficultyData = new javax.swing.JLabel();
        singleRecipeDescPanel = new javax.swing.JPanel();
        singleRecipeDescTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        singleRecipeDescData = new javax.swing.JLabel();
        singleRecipeIngrPanel = new javax.swing.JPanel();
        singleRecipeIngrTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        singleRecipeIngrData = new javax.swing.JLabel();
        singleRecipeImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(recipe.getName());
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new Dimension((int)(dim.getWidth()*0.5), (int)(dim.getHeight()*0.6)));

        singleRecipeShort.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeShort.setMaximumSize(null);
        singleRecipeShort.setMinimumSize(null);
        singleRecipeShort.setPreferredSize(new java.awt.Dimension(450, 234));

        singleRecipeTitle.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        singleRecipeTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeTitle.setText("Titel");

        singleRecipeServings.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        singleRecipeServings.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        singleRecipeServings.setText("Antal portioner:");

        singleRecipeTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        singleRecipeTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        singleRecipeTime.setText("Beräknad tid:");

        singleRecipePrice.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        singleRecipePrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        singleRecipePrice.setText("Beräknat pris:");

        singleRecipeServingsData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipeServingsData.setText("jLabel1");

        singleRecipeTimeData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipeTimeData.setText("jLabel2");

        singleRecipePriceData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipePriceData.setText("jLabel3");

        singleRecipeDifficulty.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        singleRecipeDifficulty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        singleRecipeDifficulty.setText("Svårighet:");

        singleRecipeDifficultyData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipeDifficultyData.setText("jLabel1");

        javax.swing.GroupLayout singleRecipeShortLayout = new javax.swing.GroupLayout(singleRecipeShort);
        singleRecipeShort.setLayout(singleRecipeShortLayout);
        singleRecipeShortLayout.setHorizontalGroup(
            singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeShortLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleRecipeTitle)
                    .addGroup(singleRecipeShortLayout.createSequentialGroup()
                        .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(singleRecipePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleRecipeTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleRecipeServings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleRecipeDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singleRecipeServingsData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(singleRecipeTimeData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(singleRecipePriceData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(singleRecipeDifficultyData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(267, 267, 267))
        );
        singleRecipeShortLayout.setVerticalGroup(
            singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeShortLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(singleRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRecipeServings)
                    .addComponent(singleRecipeServingsData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRecipeTime)
                    .addComponent(singleRecipeTimeData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRecipePrice)
                    .addComponent(singleRecipePriceData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(singleRecipeShortLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRecipeDifficulty)
                    .addComponent(singleRecipeDifficultyData))
                .addGap(5, 5, 5))
        );

        singleRecipeDescPanel.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeDescPanel.setMaximumSize(null);
        singleRecipeDescPanel.setMinimumSize(null);

        singleRecipeDescTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        singleRecipeDescTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeDescTitle.setText("Gör så här:");
        singleRecipeDescTitle.setMaximumSize(null);
        singleRecipeDescTitle.setMinimumSize(null);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setMaximumSize(null);
        jScrollPane2.setMinimumSize(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(277, 374));

        singleRecipeDescData.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeDescData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipeDescData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeDescData.setText("jLabel4");
        singleRecipeDescData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(singleRecipeDescData, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGap(1, 1, 1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(singleRecipeDescData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout singleRecipeDescPanelLayout = new javax.swing.GroupLayout(singleRecipeDescPanel);
        singleRecipeDescPanel.setLayout(singleRecipeDescPanelLayout);
        singleRecipeDescPanelLayout.setHorizontalGroup(
            singleRecipeDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeDescPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleRecipeDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(singleRecipeDescPanelLayout.createSequentialGroup()
                        .addComponent(singleRecipeDescTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 379, Short.MAX_VALUE)))
                .addContainerGap())
        );
        singleRecipeDescPanelLayout.setVerticalGroup(
            singleRecipeDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeDescPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(singleRecipeDescTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        singleRecipeIngrPanel.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeIngrPanel.setForeground(new java.awt.Color(204, 204, 204));
        singleRecipeIngrPanel.setMaximumSize(null);
        singleRecipeIngrPanel.setMinimumSize(null);
        singleRecipeIngrPanel.setName(""); // NOI18N
        singleRecipeIngrPanel.setPreferredSize(new java.awt.Dimension(234, 52));

        singleRecipeIngrTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        singleRecipeIngrTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeIngrTitle.setText("Ingredienser:");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        singleRecipeIngrData.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeIngrData.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        singleRecipeIngrData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeIngrData.setText("jLabel1");
        singleRecipeIngrData.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(singleRecipeIngrData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(singleRecipeIngrData, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel2);

        javax.swing.GroupLayout singleRecipeIngrPanelLayout = new javax.swing.GroupLayout(singleRecipeIngrPanel);
        singleRecipeIngrPanel.setLayout(singleRecipeIngrPanelLayout);
        singleRecipeIngrPanelLayout.setHorizontalGroup(
            singleRecipeIngrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeIngrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(singleRecipeIngrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleRecipeIngrTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        singleRecipeIngrPanelLayout.setVerticalGroup(
            singleRecipeIngrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(singleRecipeIngrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(singleRecipeIngrTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        singleRecipeImage.setBackground(new java.awt.Color(255, 255, 255));
        singleRecipeImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        singleRecipeImage.setToolTipText("");
        singleRecipeImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(singleRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(singleRecipeIngrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleRecipeDescPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(singleRecipeShort, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleRecipeShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(singleRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(singleRecipeDescPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(singleRecipeIngrPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleRecipeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleRecipeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleRecipeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleRecipeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
                public void run() {
                    RecipeDatabase db = RecipeDatabase.getSharedInstance();
                    List <Recipe> listRecipe = db.search(new SearchFilter("Svår", 30, "Grekland", 150, "Kött"));
                    new SingleRecipeView(listRecipe.get(0)).setVisible(true);  
                }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel singleRecipeDescData;
    private javax.swing.JPanel singleRecipeDescPanel;
    private javax.swing.JLabel singleRecipeDescTitle;
    private javax.swing.JLabel singleRecipeDifficulty;
    private javax.swing.JLabel singleRecipeDifficultyData;
    private javax.swing.JLabel singleRecipeImage;
    private javax.swing.JLabel singleRecipeIngrData;
    private javax.swing.JPanel singleRecipeIngrPanel;
    private javax.swing.JLabel singleRecipeIngrTitle;
    private javax.swing.JLabel singleRecipePrice;
    private javax.swing.JLabel singleRecipePriceData;
    private javax.swing.JLabel singleRecipeServings;
    private javax.swing.JLabel singleRecipeServingsData;
    private javax.swing.JPanel singleRecipeShort;
    private javax.swing.JLabel singleRecipeTime;
    private javax.swing.JLabel singleRecipeTimeData;
    private javax.swing.JLabel singleRecipeTitle;
    // End of variables declaration//GEN-END:variables
}
